# Site settings
title: HXL Blog
SEOTitle: 韩小磊的博客 | HXL Blog
header-img: img/post-bg-desk.jpg
email: hanxiaolei1119@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, HXL Blog, 韩小磊的博客, hanxiaolei, 韩小磊, C++"
url: "http://hxl.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hxl/hxl.github.io.git" # you code repository


# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  
  
